name: fabulous_analytics
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  fabulous_core:
    path: ../fabulous_core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
