name: fabulous_app

packages:
  - .
  - packages/core/*
  - packages/features/*
  - packages/supporting/*

scripts:
  analyze:
    exec: dart analyze .

  # runs "flutter pub <arg(s)>" in all packages
  pub: melos exec -c 1 -- flutter pub "$@"

ide:
  intellij:
    enabled: false
