name: fabulous_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  fabulous_core:
    path: packages/core/fabulous_core
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.2.0

flutter:
  uses-material-design: true
